filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /microservices-logs/*/*.log # Recursively capture logs in all subdirectories
      - /microservices-logs/*/*.json  # Recursively capture all JSON log files
#    paths:
#      # Paths to the logs in each microservice's logs directory
#      - ./logs/service-registry/*.log      # Logs from service 2
#      - ./logs/auth-service/*.log      # Logs from service 3
#      - ./logs/api-gateway/*.log      # Logs from service 1
#      - ./logs/appointment-service/*.log      # Logs from service 4
#      - ./logs/healthprovider-service/*.log      # Logs from service 5
#
#      # If you also want to include JSON logs, add the following:
#      - ./logs/api-gateway/*.json     # JSON logs from service 1
#      - ./logs/service-registry/*.json     # JSON logs from service 2
#      - ./logs/auth-service/*.json     # JSON logs from service 3
#      - ./logs/appointment-service/*.json     # JSON logs from service 4
#      - ./logs/healthprovider-service/*.json     # JSON logs from service 5

output.logstash:
  enabled: true
  ssl.verification_mode: none # If no SSL/TLS is set up
  hosts: ["logstash:5044"]  # Ensure this points to the Logstash service in your Docker Compose

  ## Disable output to Elasticsearch to avoid confusion
  #output.elasticsearch:
  #  enabled: false

setup.kibana:
  host: "http://kibana:5601" # Kibana host for setup