eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: 9092

spring:
  application:
    name: service-registry

management:
  health:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0