spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/healthprovider-service
  application:
    name: healthprovider-service
server:
  port: 9091

eureka:
  client:
    service-url:
      defaultZone : http://localhost:9092/eureka/

management:
  health:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0