version: '3.8'
services:
  mysql:
    container_name: appointment-mysql-container
    image: mysql:latest
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appointment_service
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"