version: '3.8'
services:
  mysql:
    container_name: appointment-mysql-container
    image: mysql:latest
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./docker/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: appointment_service
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    ports:
      - "3307:3306"
    networks:
      - microservices-network


networks:
  microservices-network:
    driver: bridge