spring:
  application:
    name: appointment-service
  datasource:
    url: jdbc:mysql://localhost:3307/appointment_service
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
server:
  port: 9090

eureka:
  client:
    service-url:
      defaultZone : http://localhost:9092/eureka/